### ISSUE TITLE
Write JOSS Paper

### ISSUE THREAD

**Issue by gomezzz** [esa/polyhedral-gravity-model#9]
- [x] Add orcid in `/paper/paper.md` @schuhmaj @FG-TUM (or post here if you are lazy :P)
- [x] Write Summary briefly describing the software
- [x] Write State of Need mentioning other works were it or other polyhedral models were used
- [x] Very roughly outline the method and where more details can be found
- [x] Briefly describe installation, how people can contribute and where usage instructions can be found
- [x] Add links conda, github, readthedocs

**Comment by FG-TUM** [comment]
I can't edit directly :P
My ORCID `0000-0001-5195-7919`

**Comment by schuhmaj** [comment]
Created and Added `0009-0005-9693-4530` to the PR

**Comment by schuhmaj** [comment]
@gomezzz All done. Can we close this issue or shall we keep it open for now?
